# Generated by Django 4.2.1 on 2023-06-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='address',
            new_name='adress',
        ),
    ]
