# Generated by Django 4.2.1 on 2023-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_rename_address_stock_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='adress',
            new_name='address',
        ),
    ]
